uri_templates:
  index:          http://{lang}pinto.jp/
  signup_openid:  http://{lang}pinto.jp/signup_forms/openid
  signup_auth:    http://{lang}pinto.jp/signup_forms/auth{query}
  signup_account: http://{lang}pinto.jp/signup_forms/account{query}
  users:          http://{lang}pinto.jp/users
  user:           http://{lang}pinto.jp/users/{username}

openid_providers:
  - yahoo.com
  - yahoo.co.jp
  - myopenid.com
