app_name: Pinto

mode: production

routes:
  index:          http://{locale_code}pinto.jp/
  signup_openid:  http://{locale_code}pinto.jp/signup_forms/openid
  signup_auth:    http://{locale_code}pinto.jp/signup_forms/auth{query_string}
  signup_account: http://{locale_code}pinto.jp/signup_forms/account{query_string}
  users:          http://{locale_code}pinto.jp/users
  user:           http://{locale_code}pinto.jp/users/{user_name}

openid_providers:
  - yahoo.com
  - yahoo.co.jp
  - myopenid.com
